#pragma once
#include <Net/Net/Net.h>

#ifdef NET_DISABLE_IMPORT_KERNEL32
#define Kernel32
#else
#include <Net/Import/Definition.hpp>

namespace Net
{
	IMPORT_BEGIN(Kernel32);
	IMPORT_DEFINE_FNC_WINAPI(HRSRC, FindResourceA, HMODULE, LPCSTR, LPCSTR);
	IMPORT_DEFINE_FNC_WINAPI(HRSRC, FindResourceW, HMODULE, const wchar_t*, const wchar_t*);
	IMPORT_DEFINE_FNC_WINAPI(HGLOBAL, LoadResource, HMODULE, HRSRC);
	IMPORT_DEFINE_FNC_WINAPI(DWORD, SizeofResource, HMODULE, HRSRC);
	IMPORT_DEFINE_FNC_WINAPI(LPVOID, LockResource, HGLOBAL);
	IMPORT_DEFINE_FNC_WINAPI(HMODULE, LoadLibraryA, LPCSTR);
	IMPORT_DEFINE_FNC_WINAPI(HMODULE, LoadLibraryW, const wchar_t*);
	IMPORT_DEFINE_FNC_WINAPI(FARPROC, GetProcAddress, HMODULE, LPCSTR);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, FreeLibrary, HMODULE);
	IMPORT_DEFINE_FNC_WINAPI(void, Sleep, DWORD);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, K32EnumProcesses, DWORD*, DWORD, LPDWORD);
	IMPORT_DEFINE_FNC_WINAPI(HANDLE, OpenProcess, DWORD, BOOL, DWORD);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, K32EnumProcessModules, HANDLE, HMODULE*, DWORD, LPDWORD);
	IMPORT_DEFINE_FNC_WINAPI(DWORD, K32GetModuleBaseNameA, HANDLE, HMODULE, LPSTR, DWORD);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, CheckRemoteDebuggerPresent, HANDLE, PBOOL);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, IsDebuggerPresent);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, GetVersionExA, LPOSVERSIONINFOA);
	IMPORT_DEFINE_FNC_WINAPI(HMODULE, GetModuleHandleA, LPCSTR);
	IMPORT_DEFINE_FNC_WINAPI(DWORD, GetModuleFileNameA, HMODULE, LPSTR, DWORD);
	IMPORT_DEFINE_FNC_WINAPI(LPVOID, MapViewOfFile, HANDLE, DWORD, DWORD, DWORD, SIZE_T);
	IMPORT_DEFINE_FNC_WINAPI(HANDLE, CreateFileMappingA, HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR);
	IMPORT_DEFINE_FNC_WINAPI(HANDLE, CreateFileA, LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, UnmapViewOfFile, LPCVOID);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, CloseHandle, HANDLE);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, GetThreadContext, HANDLE, LPCONTEXT);
	IMPORT_DEFINE_FNC_WINAPI(BOOL, SetThreadContext, HANDLE, const CONTEXT*);
	IMPORT_DEFINE_FNC_WINAPI(DWORD, ResumeThread, HANDLE);
	IMPORT_DEFINE_FNC_WINAPI(HANDLE, GetCurrentThread);
	IMPORT_END
};
#endif
